name: arXiv Email Notifier

on:
  schedule:
    - cron: '5 0 * * *'       # 00:05 UTC --> 09:05 KST
  workflow_dispatch:           # 수동 실행 허용

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 요약을 켜 둔 상태(AI_SUMMARIZE = True)라면 openai까지 설치
      - name: Install deps
        run: pip install feedparser openai

      - name: Send arXiv digest
        env:
          EMAIL_ADDRESS:   ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD:  ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL:        ${{ secrets.TO_EMAIL }}
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}   # AI_SUMMARIZE=True일 때만 필요
        run: |
          python arxiv_notifier.py
