name: arXiv Email Notifier

on:
  schedule:
    - cron: '0 0 * * *'       # 00:00 UTC --> 09:00 KST
  workflow_dispatch: 
    inputs:
      window_days:
        description: 'Time window in days'
        required: false
        default: '1'
        type: string

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 요약을 켜 둔 상태(AI_SUMMARIZE = True)라면 openai까지 설치
      - name: Install deps
        run: pip install feedparser openai

      - name: Send arXiv digest
        env:
          EMAIL_ADDRESS:   ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD:  ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL:        ${{ secrets.TO_EMAIL }}
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}   # AI_SUMMARIZE=True일 때만 필요
        run: |
          python arxiv_notifier.py
          