# .github/workflows/arxiv-notifier.yml
name: arXiv-notifier CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WINDOW_DAYS: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install feedparser openai

      - run: |
          python arxiv_notifier_test.py | tee digest.log

      - uses: actions/upload-artifact@v4
        with:
          name: arxiv-digest-${{ github.run_number }}
          path: artifacts/

      - run: |
          echo '### 📰 Daily arXiv Digest (dry-run)' >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          if [ -f artifacts/email.txt ]; then
            cat artifacts/email.txt >> "$GITHUB_STEP_SUMMARY"
          elif [ -f arxiv_notifier/artifacts/email.txt ]; then
            cat arxiv_notifier/artifacts/email.txt >> "$GITHUB_STEP_SUMMARY"
          else
            echo '_no email.txt generated_' >> "$GITHUB_STEP_SUMMARY"
          fi
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo '```text' >> "$GITHUB_STEP_SUMMARY"
          cat digest.log >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo '---' >> "$GITHUB_STEP_SUMMARY"
