name: arXiv-notifier CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dry-run:
    runs-on: ubuntu-latest

    env:      # secrets only needed for GPT summaries
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WINDOW_DAYS: 5

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser openai

      - name: Run notifier in dry-run mode
        run: |
          python arxiv_notifier_test.py | tee digest.log

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: arxiv-digest-${{ github.run_number }}
          path: artifacts/

      - name: Add e-mail to Job Summary
        run: |
          echo '### 📰 Daily arXiv Digest (dry-run)' >> $GITHUB_STEP_SUMMARY
          echo '```'                     >> $GITHUB_STEP_SUMMARY
          cat artifacts/email.txt        >> $GITHUB_STEP_SUMMARY
          echo '```'                     >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat digest.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '---' >> $GITHUB_STEP_SUMMARY

